export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_REDIRECT_ROUTE = 'SET_REDIRECT_ROUTE';
